name: Deploy

on:
  push:
    branches:
      - main
      - initial-commit

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          docker compose up -d --build --remove-orphans
      - name: Cleanup
        run: docker image prune -f
